### PR TITLE
Add script based on labeled cubes

### PR DESCRIPTION
**Pull request by natescherer**
Hello! This is an amazing script and not something I ever would have thought of on my own. I was inspired by your work, however, to cook up a modified version that uses the labeled multiplier cubes from https://github.com/AndrewEllis93/Print-Tuning-Guide/tree/main/test_prints/extrusion_multiplier_cubes/labeled to automatically set the multiplier for each object based upon the name of the file.

I've tested and it seems to work well, so thought I'd shoot a PR your way to see if you'd like to add this to your repo. If you're interested, I can also write up some documentation for this. Thanks!

### CODE REVIEW

**Comment by natescherer** [comment]
Updated this a bit to now be able to be called directly from PrusaSlicer as part of the slicing process.

**Comment by myevo8u** [comment]
I merged it in! I haven't had a chance to look everything over in depth, but it looks good! Hopefully I should have some free time coming up in the next couple of weeks!

**Comment by natescherer** [comment]
Cool! I'll write up some doc for this and contribute it, too.

**Comment by kozross** [comment]
So is this script already usable? If so, how?

**Comment by natescherer** [comment]
Hi @kozross, sorry this took so long to respond to, but I've added documentation in #2

**Pull request merged**
